### ISSUE TITLE
encoding UTF-8

### ISSUE THREAD

**Issue by karolina-m** [pikrol/CDI#3]
Super jest to zrobione! Nie wiem czy to ma duże znaczenie, ale mój R nie ma ustawionego UTF-8 jako default encoding i mi się polskie znaki wykrzaczały. Musiałam pójść File --> Reopen with Encoding --> UTF-8 i jest ok. A więc: warto automatycznie wymusić otwieranie kodu z UTF-8.

PS. Widzę, że lista itemów (csv) ma argument encoding = "UTF-8". Może wystarczy dodać encoding = "UTF-8" do options() żeby to było globalne? Coś podobnego tu: https://github.com/vnijs/radiant/issues/25

**Comment by pikrol** [comment]
Aplikacja będzie uruchamiana docelowo na serwerze, więc narazie to raczej nie problem.
