### ISSUE TITLE
Ponowne wejście w daną część CDI a dotychczasowe odpowiedzi

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI#5]
Wspomniałem o tym tutaj #4, ale to mega ważne, wręcz chyba kluczowe, bo jeśli ponowne wejście kasuje poprzednie odpowiedzi, to może powinniśmy jeszcze przemyśleć problem cofania i #4:

> Rodzic powinien mieć możliwość ponownego wejścia w daną część, ale źle by było, gdyby to oznaczało konieczność ponownego wprowadzania *wszystkich* odpowiedzi (łącznie z polem na uwagi).

Chyba że to nie problem?

**Comment by karolina-m** [comment]
Przepraszam, że tak późno! Zdecydowanie powinniśmy pozwolić rodzicom na nawigowanie bez utraty odpowiedzi; i ten pasek postępu też jest ważny (bo statystyczny irmik jest długi, nie chcemy żeby ktoś zrezygnował przed końcem ;)).
Jeśli chodzi o oddzielne części kwestionariusza, tu nie mam silnego zdania.
