### ISSUE TITLE
Przenosimy issues, zamykamy repo?

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI#6]
Te githubowe projekty jednak nie są taką fajną opcją dla nas, jak myślałem na początku. One są raczej na potrzeby pojedynczego użytkownika (żeby dotrzeć do projektu StarWords, muszę doklikać się do profilu @pikrol najpierw) albo organizacji (więc musielibyśmy stworzyć organizację najpierw). Podstawową i centralną jednostką na GitHubie jest chyba jednak repo, więc może tego się (na razie) trzymajmy.

Rozumiem, że to repo porzucamy/zamykamy/whatever? W takim wypadku proponuję, żebyśmy przejrzeli wszystkie otwarte tutaj issues i dla każdego zrobili jedną z dwóch rzeczy:
- zamknęli je, jeśli się zdezaktualizowało,
- przetransferowali je do [nowego repo](https://github.com/pikrol/CDI-static).

W momencie, kiedy to będzie jedyne otwarte tutaj issue, będzie można je zamknąć :)

**Comment by pikrol** [comment]
Zrobione
